### ISSUE TITLE
[ Improvement ] Don't create unnecessary files

### ISSUE THREAD

**Issue by ghost** [arnehilmann/coltrace#1]
First of all, thanks for creating this tool!
i think people should opt in for what file type the tool creates.
i provided one PNG and it outputted 17 files for which i only needed one file

**Comment by arnehilmann** [comment]
Hi!
How did you determine which file you needed?
And how would you specify that on the command line?

**Comment by ghost** [comment]
well, the utility is called "coltrace", you would imagine it to do the same as potrace but with colors, resulting in a svg file,
it should be the default option to output svg files, if you designed it to do other things it should be up to you the implementation, there is my recommendation

**Comment by arnehilmann** [comment]
Ok, so I think about removing those tmp files (when not in DEBUG mode), resulting only in the b/w and color svg...

**Comment by arnehilmann** [comment]
BTW: coltrace is quite old (and unpolished) and there seems to be a newer/better alternative available now (I will update the README accordingly):

https://github.com/visioncortex/vtracer

Perhaps you could give that a try and comment on it here?!
